# Generated by Django 4.1.5 on 2023-10-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0004_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
