# Generated by Django 4.1.5 on 2023-10-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('examapp', '0007_rename_position_customuser_actype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['username'], 'permissions': []},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users_profile', to='auth.group'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_profile_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='actype',
            field=models.CharField(choices=[('admin', 'Admin'), ('centers', 'Centers'), ('examiner', 'Examiner')], max_length=10),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
