# Generated by Django 4.1.5 on 2023-10-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('examapp', '0008_alter_userprofile_options_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='actype',
            field=models.CharField(choices=[('admin', 'Admin'), ('centers', 'Centers'), ('examiner', 'Examiner')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_profile', to='auth.group'),
        ),
    ]
